# MPV custom services

run_command:
  name: Run command
  description: Run an arbitrary MPV command.
  target:
    entity:
      integration: mpv
      domain: media_player
  fields:
    command_string:
      name: Command String
      description: Complete MPV command string including parameters (e.g. "seek 30 absolute", "set fullscreen yes").
      required: true
      example: "set fullscreen yes"
      selector:
        text: